PhamDuyLoi_222601120/Controllers/BTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PhamDuyLoi_222601120.Models;

namespace PhamDuyLoi_222601120.Controllers
{
    public class BTController : Controller
    {
        private readonly QlhangHoaContext _context;

        public BTController(QlhangHoaContext context)
        {
            _context = context;
        }
        public IActionResult Loc(int mid)
        {
            var listhang = _context.HangHoas.Where(s => s.MaLoai == mid).Include(s => s.MaLoaiNavigation).ToList();
            return PartialView("~/Views/BT/ProductTable.cshtml", listhang);

        }
        // GET: BT
        public async Task<IActionResult> Index()
        {
            var listhang = _context.HangHoas.Where(s => s.Gia >= 100).ToList();
            return View(listhang);
        }

        // GET: BT/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas
                .Include(h => h.MaLoaiNavigation)
                .FirstOrDefaultAsync(m => m.MaHang == id);
            if (hangHoa == null)
            {
                return NotFound();
            }

            return View(hangHoa);
        }

        // GET: BT/Create
        public IActionResult Create()
        {
            ViewData["MaLoai"] = new SelectList(_context.LoaiHangs, "MaLoai", "TenLoai");
            return View();
        }

        // POST: BT/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHang,MaLoai,TenHang,Gia,Anh")] HangHoa hangHoa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hangHoa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoai"] = new SelectList(_context.LoaiHangs, "MaLoai", "TenLoai", hangHoa.MaLoai);
            return View(hangHoa);
        }

        // GET: BT/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas.FindAsync(id);
            if (hangHoa == null)
            {
                return NotFound();
            }
            ViewData["MaLoai"] = new SelectList(_context.LoaiHangs, "MaLoai", "MaLoai", hangHoa.MaLoai);
            return View(hangHoa);
        }

        // POST: BT/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaHang,MaLoai,TenHang,Gia,Anh")] HangHoa hangHoa)
        {
            if (id != hangHoa.MaHang)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hangHoa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HangHoaExists(hangHoa.MaHang))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoai"] = new SelectList(_context.LoaiHangs, "MaLoai", "MaLoai", hangHoa.MaLoai);
            return View(hangHoa);
        }

        // GET: BT/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas
                .Include(h => h.MaLoaiNavigation)
                .FirstOrDefaultAsync(m => m.MaHang == id);
            if (hangHoa == null)
            {
                return NotFound();
            }

            return View(hangHoa);
        }

        // POST: BT/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hangHoa = await _context.HangHoas.FindAsync(id);
            if (hangHoa != null)
            {
                _context.HangHoas.Remove(hangHoa);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HangHoaExists(int id)
        {
            return _context.HangHoas.Any(e => e.MaHang == id);
        }
    }
}

PhamDuyLoi_222601120/Views/BT/Create.cshtml
@model PhamDuyLoi_222601120.Models.HangHoa

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/PhamDuyLoi_Layout.cshtml";
}

<h1>Phạm Duy Lợi</h1>

<h4>Thêm hàng hóa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaLoai" class="control-label"></label>
                <select asp-for="MaLoai" class ="form-control" asp-items="ViewBag.MaLoai"></select>
            </div>
            <div class="form-group">
                <label asp-for="TenHang" class="control-label"></label>
                <input asp-for="TenHang" class="form-control" />
                <span asp-validation-for="TenHang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gia" class="control-label"></label>
                <input asp-for="Gia" class="form-control" />
                <span asp-validation-for="Gia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anh" class="control-label"></label>
                <input asp-for="Anh" class="form-control" />
                <span asp-validation-for="Anh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PhamDuyLoi_222601120/Views/BT/Delete.cshtml
@model PhamDuyLoi_222601120.Models.HangHoa

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/PhamDuyLoi_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HangHoa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenHang)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenHang)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaLoaiNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaLoaiNavigation.MaLoai)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaHang" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PhamDuyLoi_222601120/Views/BT/Details.cshtml
@model PhamDuyLoi_222601120.Models.HangHoa

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/PhamDuyLoi_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>HangHoa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenHang)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenHang)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaLoaiNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaLoaiNavigation.MaLoai)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaHang">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PhamDuyLoi_222601120/Views/BT/Edit.cshtml
@model PhamDuyLoi_222601120.Models.HangHoa

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/PhamDuyLoi_Layout.cshtml";
}

<h1>Edit</h1>

<h4>HangHoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaHang" />
            <div class="form-group">
                <label asp-for="MaLoai" class="control-label"></label>
                <select asp-for="MaLoai" class="form-control" asp-items="ViewBag.MaLoai"></select>
                <span asp-validation-for="MaLoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenHang" class="control-label"></label>
                <input asp-for="TenHang" class="form-control" />
                <span asp-validation-for="TenHang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gia" class="control-label"></label>
                <input asp-for="Gia" class="form-control" />
                <span asp-validation-for="Gia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anh" class="control-label"></label>
                <input asp-for="Anh" class="form-control" />
                <span asp-validation-for="Anh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PhamDuyLoi_222601120/Views/BT/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/PhamDuyLoi_Layout.cshtml";
}
@model IEnumerable<HangHoa>
<div class="content_top">
	<div class="heading">
		<h3>Phạm Duy Lợi</h3>
	</div>
	<div class="see">
		<p><a href="#">See all Products</a></p>
	</div>
	<div class="clear"></div>
</div>
<div id="content">
	<div class="section group">
		@foreach (var s in Model)
		{
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="~/images/@s.Anh" alt="" /></a>
				<h2>@s.TenHang</h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$@s.Gia</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
		}
	</div>
</div>
<!-- End New Product -->
<!-- Begin Feature Products -->
<div class="content_bottom">
	<div class="heading">
		<h3>Feature Products</h3>
	</div>
	<div class="see">
		<p><a href="#">See all Products</a></p>
	</div>
	<div class="clear"></div>
</div>
<div class="section group">
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/new-pic1.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$849.99</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/new-pic2.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$599.99</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/new-pic4.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$799.99</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/new-pic3.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$899.99</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<!-- End Feature Products -->
@section Scripts {
	<script>
		$("li").click(function(e) {
			var id = $(this).attr("id");
			$.ajax({
				url: "@Url.Action("Loc", "BT")",
				data: { mid: id },
				success: function(reponse) {
					$("div#content").html(reponse);
				}
			});
		});
	</script>
}

PhamDuyLoi_222601120/Views/BT/ProductTable.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<HangHoa>
<div class="section group">
	@foreach (var s in Model)
	{
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="~/images/@s.Anh" alt="" /></a>
			<h2>@s.TenHang</h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$@s.Gia</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	}
</div>