PhamDuyLoi_222601120/ViewComponents/NavViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PhamDuyLoi_222601120.Models;

namespace PhamDuyLoi_222601120.ViewComponents
{
    public class NavViewComponent:ViewComponent
    {
        private readonly QlhangHoaContext _context;

        public NavViewComponent(QlhangHoaContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            var listloai = _context.LoaiHangs.ToList();
            return View("RenderNav", listloai);
        }
    }
}

PhamDuyLoi_222601120/Views/Shared/PhamDuyLoi_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE HTML>
<head>
	<title>Free Home Shoppe Website Template | Home :: w3layouts</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
</head>
<body>
	<!-- Begin Wrap -->
	<div class="wrap">
		<!-- Begin Header -->
		@await Component.InvokeAsync("Nav")
		<!-- End Header -->
		<!-- Begin Main -->
		<div class="main">
			<div class="content">
				@RenderBody()
			</div>
		</div>
		<!-- End Main -->
	</div>
	<!-- End Wrap -->
	<!-- Begin Footer -->
	<partial name="PhamDuyLoi_footer"/>
	<!-- End Footer -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	@RenderSection("Scripts", required:false);
</body>
</html>

PhamDuyLoi_222601120/Views/Shared/PhamDuyLoi_footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="footer">
	<div class="wrap">
		<div class="section group">
			<div class="col_1_of_4 span_1_of_4">
				<h4>Information</h4>
				<ul>
					<li><a href="about.html">About Us</a></li>
					<li><a href="contact.html">Customer Service</a></li>
					<li><a href="#">Advanced Search</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>Why buy from us</h4>
				<ul>
					<li><a href="about.html">About Us</a></li>
					<li><a href="contact.html">Customer Service</a></li>
					<li><a href="#">Privacy Policy</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>My account</h4>
				<ul>
					<li><a href="contact.html">Sign In</a></li>
					<li><a href="index.html">View Cart</a></li>
					<li><a href="#">My Wishlist</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>Contact</h4>
				<ul>
					<li><span>+91-123-456789</span></li>
					<li><span>+00-123-000000</span></li>
				</ul>
			</div>
		</div>
	</div>
</div>

PhamDuyLoi_222601120/Views/Shared/PhamDuyLoi_header.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="header">
	<div class="header_top">
		<div class="logo">
			<a href="index.html"><img src="~/images/logo.png" alt="" /></a>
		</div>
		<div class="cart">
			<p>
				Welcome to our Online Store! <span>Cart:</span><div id="dd" class="wrapper-dropdown-2">
					0 item(s) - $0.00
					<ul class="dropdown">
						<li>you have no items in your Shopping cart</li>
					</ul>
				</div>
			</p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="header_bottom">
		<div class="menu">
			<ul>
				<li class="active"><a href="index.html">Home</a></li>
				<li><a href="about.html">About</a></li>
				<li><a href="delivery.html">Delivery</a></li>
				<li><a href="news.html">News</a></li>
				<li><a href="contact.html">Contact</a></li>
				<div class="clear"></div>
			</ul>
		</div>
		<div class="search_box">
			<form>
				<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
				<input type="button" value="">
			</form>
		</div>
		<div class="clear"></div>
	</div>
</div>

PhamDuyLoi_222601120/Views/Shared/PhamDuyLoi_main.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<!-- Begin New Product -->
<div class="content_top">
	<div class="heading">
		<h3>New Products</h3>
	</div>
	<div class="see">
		<p><a href="#">See all Products</a></p>
	</div>
	<div class="clear"></div>
</div>
<div class="section group">
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/feature-pic1.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$620.87</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/feature-pic2.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$899.75</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/feature-pic3.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$599.00</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/feature-pic4.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$679.87</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/feature-pic4.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$679.87</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<!-- End New Product -->
<!-- Begin Feature Products -->
<div class="content_bottom">
	<div class="heading">
		<h3>Feature Products</h3>
	</div>
	<div class="see">
		<p><a href="#">See all Products</a></p>
	</div>
	<div class="clear"></div>
</div>
<div class="section group">
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/new-pic1.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$849.99</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/new-pic2.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$599.99</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/new-pic4.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$799.99</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/new-pic3.jpg" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$899.99</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<!-- End Feature Products -->

PhamDuyLoi_222601120/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhamDuyLoi_222601120</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhamDuyLoi_222601120.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhamDuyLoi_222601120</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PhamDuyLoi_222601120 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>